import { TokenRow } from "@/types/token";

export const tokenRows: TokenRow[] = [
  {
    id: "1",
    symbol: "BORK",
    name: "Bork Inu",
    chain: "Solana",
    marketCapHigh: 162000000,
    currentMarketCap: 4200000,
    drawdownPercent: 97.41,
    resurrectionScore: 86,
    status: "resurrection",
  },
  {
    id: "2",
    symbol: "JOLT",
    name: "Jolt Labs",
    chain: "Solana",
    marketCapHigh: 91000000,
    currentMarketCap: 3800000,
    drawdownPercent: 95.82,
    resurrectionScore: 68,
    status: "zombie",
  },
  {
    id: "3",
    symbol: "DUST",
    name: "Dust Bazaar",
    chain: "Solana",
    marketCapHigh: 54000000,
    currentMarketCap: 620000,
    drawdownPercent: 98.85,
    resurrectionScore: 34,
    status: "dead",
  },
  {
    id: "4",
    symbol: "REEF",
    name: "Reef Kitty",
    chain: "Solana",
    marketCapHigh: 128000000,
    currentMarketCap: 3600000,
    drawdownPercent: 97.19,
    resurrectionScore: 79,
    status: "resurrection",
  },
  {
    id: "5",
    symbol: "MINT",
    name: "Mint Forge",
    chain: "Solana",
    marketCapHigh: 67000000,
    currentMarketCap: 1500000,
    drawdownPercent: 97.76,
    resurrectionScore: 57,
    status: "zombie",
  },
  {
    id: "6",
    symbol: "SPLAT",
    name: "Splat Monkey",
    chain: "Solana",
    marketCapHigh: 74000000,
    currentMarketCap: 930000,
    drawdownPercent: 98.74,
    resurrectionScore: 31,
    status: "dead",
  },
  {
    id: "7",
    symbol: "WAVE",
    name: "Wavelet Finance",
    chain: "Solana",
    marketCapHigh: 142000000,
    currentMarketCap: 5800000,
    drawdownPercent: 95.92,
    resurrectionScore: 73,
    status: "zombie",
  },
  {
    id: "8",
    symbol: "NOVA",
    name: "Nova Burrow",
    chain: "Solana",
    marketCapHigh: 47000000,
    currentMarketCap: 1800000,
    drawdownPercent: 96.17,
    resurrectionScore: 62,
    status: "zombie",
  },
  {
    id: "9",
    symbol: "VOID",
    name: "Void Rabbits",
    chain: "Solana",
    marketCapHigh: 69000000,
    currentMarketCap: 510000,
    drawdownPercent: 99.26,
    resurrectionScore: 25,
    status: "dead",
  },
  {
    id: "10",
    symbol: "PUMP",
    name: "Pump Harbor",
    chain: "Solana",
    marketCapHigh: 52000000,
    currentMarketCap: 3000000,
    drawdownPercent: 94.23,
    resurrectionScore: 81,
    status: "resurrection",
  },
  {
    id: "11",
    symbol: "CRAB",
    name: "Crab Yard",
    chain: "Solana",
    marketCapHigh: 84000000,
    currentMarketCap: 920000,
    drawdownPercent: 98.90,
    resurrectionScore: 30,
    status: "dead",
  },
  {
    id: "12",
    symbol: "FLIP",
    name: "Flip Relay",
    chain: "Solana",
    marketCapHigh: 39000000,
    currentMarketCap: 2500000,
    drawdownPercent: 93.59,
    resurrectionScore: 76,
    status: "resurrection",
  },
  {
    id: "13",
    symbol: "RUGR",
    name: "Rug Runner",
    chain: "Solana",
    marketCapHigh: 62000000,
    currentMarketCap: 780000,
    drawdownPercent: 98.74,
    resurrectionScore: 36,
    status: "dead",
  },
  {
    id: "14",
    symbol: "ECHO",
    name: "Echo Meme",
    chain: "Solana",
    marketCapHigh: 93000000,
    currentMarketCap: 3200000,
    drawdownPercent: 96.56,
    resurrectionScore: 59,
    status: "zombie",
  },
  {
    id: "15",
    symbol: "GRIT",
    name: "Grit DAO",
    chain: "Solana",
    marketCapHigh: 43000000,
    currentMarketCap: 350000,
    drawdownPercent: 99.19,
    resurrectionScore: 22,
    status: "dead",
  },
];
